✨ Create deployment template for helm chart
kubernetes-sigs/cluster-api-operator pull request #199
Opened 2023-07-27 21:37 UTC by Fedosin

**What this PR does / why we need it**:
This PR makes capi operator deployment manifest customizable. E.g. you can set custom image or modify resource limits, and so on.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #171

2023-07-28 10:14 UTC, Fedosin commented
/hold

need to update release image setting https://github.com/kubernetes-sigs/cluster-api-operator/blob/main/Makefile#L414-L418

2023-07-28 10:43 UTC, Fedosin commented
/hold cancel

2023-07-28 11:37 UTC, alexander-demicev requested changes
thanks, looks good just one minor comment

2023-07-28 11:37 UTC, alexander-demicev commented on Makefile
> +	yq eval '.image.manager.pullPolicy = "$(PULL_POLICY)"' $(TARGET_RESOURCE) -i
can you make `yq` a local dependency like all other binaries we are using?

2023-07-31 16:55 UTC, Fedosin commented
/retest

2023-08-03 09:18 UTC, alexander-demicev reviewed
/approve

2023-08-03 12:34 UTC, Danil-Grigorev reviewed
Some missing defaults which I think need to be added, but overall looks good

2023-08-03 12:34 UTC, Danil-Grigorev commented on hack/charts/cluster-api-operator/templates/deployment.yaml
> +  replicas: {{ .Values.replicaCount }}
This value does not have default, please add it to values.yaml

2023-08-03 12:34 UTC, Danil-Grigorev commented on hack/charts/cluster-api-operator/templates/deployment.yaml
> +      {{- with .Values.tolerations }}
These values seems to be missing from values.yaml too

2023-08-03 12:34 UTC, Danil-Grigorev commented on hack/charts/cluster-api-operator/templates/deployment.yaml
> +      affinity:
Here as well

2023-08-04 13:21 UTC, Danil-Grigorev approved these changes
/lgtm

2023-08-04 13:21 UTC, furkatgofurov7 reviewed
/lgtm

2023-08-04 13:34 UTC, merged